(()=>{'use strict';const $=(s,r=document)=>r.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let resourceErrors=[];addEventListener('error',e=>{let x=e.target;if(x&&x!==window&&x.src||x?.href)resourceErrors.push(x.src||x.href)},true);
async function run(){let box=$('#k408-checks');if(!box)return;box.innerHTML='<div class="k408-check"><i class="k408-dot"></i><b>正在诊断</b><span>请稍候…</span></div>';let a=[],add=(name,status,detail)=>a.push({name,status,detail});
add('JavaScript 执行','ok','诊断脚本已正常运行');add('HTTPS',location.protocol==='https:'||location.hostname==='localhost'?'ok':'warn',location.protocol==='https:'?'当前连接使用 HTTPS':'当前不是 HTTPS 连接');
try{let k='k408:diag:test';localStorage.setItem(k,'1');localStorage.removeItem(k);add('本地存储','ok','localStorage 可读写')}catch(e){add('本地存储','bad','不可用：'+e.message)}
let ids=[...document.querySelectorAll('[id]')].map(x=>x.id),dup=[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))];add('重复元素 ID',dup.length?'warn':'ok',dup.length?'发现：'+dup.join(', '):'当前页面未发现重复 ID');
let src=[...document.scripts].map(x=>x.src).filter(Boolean),dups=[...new Set(src.filter((x,i)=>src.indexOf(x)!==i))];add('重复脚本',dups.length?'warn':'ok',dups.length?'发现重复：'+dups.join(', '):'未发现相同 URL 的脚本重复加载');
for(let [name,path] of [['搜索索引','/search.json'],['学习工具脚本','/js/study-tools.js'],['学习工具样式','/css/study-tools.css'],['批注脚本','/js/annotations.js'],['科技主题脚本','/js/tech.js']]){try{let r=await fetch(path,{method:'GET',cache:'no-store'});add(name,r.ok?'ok':'bad',path+' — HTTP '+r.status)}catch(e){add(name,'bad',path+' — '+e.message)}}
add('页面资源错误',resourceErrors.length?'bad':'ok',resourceErrors.length?resourceErrors.join('；'):'本次诊断期间未捕获资源加载失败');add('Service Worker','serviceWorker'in navigator?(navigator.serviceWorker.controller?'ok':'warn'):'warn','serviceWorker'in navigator?(navigator.serviceWorker.controller?'已控制当前页面':'浏览器支持，但当前页面未被控制'):'当前浏览器不支持');
let counts=a.reduce((o,x)=>(o[x.status]++,o),{ok:0,warn:0,bad:0});$('#k408-ok').textContent=counts.ok;$('#k408-warn').textContent=counts.warn;$('#k408-bad').textContent=counts.bad;box.innerHTML=a.map(x=>`<div class="k408-check ${x.status}"><i class="k408-dot"></i><b>${esc(x.name)}</b><span>${esc(x.detail)}</span></div>`).join('');$('#k408-diag-time').textContent='最近诊断：'+new Date().toLocaleString()}
document.addEventListener('DOMContentLoaded',()=>{$('#k408-run-diag')?.addEventListener('click',run);run()});})();
